bouton create account
Unitystation-fork/Unitystation-MillstoneSteam pull request #120
Opened 2024-03-25 11:58 UTC by KarimRahoMekdad

J'ai ajouter ce code dans le fichier Header.vue du dossier components:
<div class="btns">
    <a href="https://vu.fr/mGJw">
        <button>Create account</button>
    </a>
</div>
Il ajoute le bouton create account lié a l'adresse https du formulaire google doc.

2024-03-25 12:05 UTC, Fr-Dae commented
@KarimRahoMekdad tu peux ajouté une capture ecran du resultat en local ?
es-ce que le bouton disparais une fois connecter ?

2024-03-25 13:00 UTC, KarimRahoMekdad commented
![Capture d'écran 2024-03-25 133118](https://github.com/Unitystation-fork/Unitystation-MillstoneSteam/assets/147518840/eb680783-ee82-4b15-a72f-d83732693eae)

Voila ce que le bouton donne, il ne disparait pas après et une fois le formulaire remplis on ne retourne pas sur la page milestone.
Je pense faire en sorte que le formulaire s'ouvre dans une 2ème page .

2024-03-25 13:40 UTC, Fr-Dae commented on components/Header.vue
> +      <a href="https://vu.fr/mGJw">
<a href="https://vu.fr/mGJw" target="_blank">

2024-03-25 13:40 UTC, Fr-Dae requested changes
<a href="https://vu.fr/mGJw" target="_blank">

2024-03-25 13:42 UTC, Fr-Dae commented
en plus du blanck il faut que le bouton "creer un compte" ne soit afficher que lorsque l'utilisateur n'est pas connecter.

2024-03-27 09:35 UTC, Fr-Dae approved these changes

2024-03-29 16:27 UTC, KarimRahoMekdad commented
J'ai simplifié le code que j'avais fait, maintenant le bouton CREATE ACCOUNT est lié a la connexion(login), il disparait quand l'utilisateur se connecte et reste non apparent même après avoir rafraichie la page.

2024-04-02 15:34 UTC, merged